// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6FoOYTCEsTg6usec--ldRa48moqV-cw4',
    appId: '1:904111637056:web:e426ed6d2b54b0022f95a5',
    messagingSenderId: '904111637056',
    projectId: 'nirvana-foods-d9ef5',
    authDomain: 'nirvana-foods-d9ef5.firebaseapp.com',
    storageBucket: 'nirvana-foods-d9ef5.appspot.com',
    measurementId: 'G-L1QXPPMYRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgWeaU3t41w_-7VwQwtqtxzHtsTuAJLEk',
    appId: '1:904111637056:android:ff7c8e5ad63f9adc2f95a5',
    messagingSenderId: '904111637056',
    projectId: 'nirvana-foods-d9ef5',
    storageBucket: 'nirvana-foods-d9ef5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaDlpE7csBxUAaY-aLteieoQ3jijBj2wo',
    appId: '1:904111637056:ios:88bdf3788f51f5ff2f95a5',
    messagingSenderId: '904111637056',
    projectId: 'nirvana-foods-d9ef5',
    storageBucket: 'nirvana-foods-d9ef5.appspot.com',
    iosClientId: '904111637056-b4aoeiv1r54h9biaevejfs4l129pks9c.apps.googleusercontent.com',
    iosBundleId: 'com.kazungudev.nirvanafoodsAdminPanelWebapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaDlpE7csBxUAaY-aLteieoQ3jijBj2wo',
    appId: '1:904111637056:ios:4316e1113f7588332f95a5',
    messagingSenderId: '904111637056',
    projectId: 'nirvana-foods-d9ef5',
    storageBucket: 'nirvana-foods-d9ef5.appspot.com',
    iosClientId: '904111637056-ccnpra650d835if9o09ipi2re6er5grn.apps.googleusercontent.com',
    iosBundleId: 'com.kazungudev.nirvanafoodsAdminPanelWebapp.RunnerTests',
  );
}
